import { defineConfig } from 'cspell'

export default defineConfig({
  words: [
    'azat',
    'borrowable',
    'browserslistrc',
    'changelogen',
    'changelogithub',
    'crosspost',
    'frontmatter',
    'grotesk',
    'humanwhocodes',
    'joshuakgoldberg',
    'keyux',
    'libc',
    'llms',
    'lightningcss',
    'mdast',
    'mdxjs',
    'minisearch',
    'nanostores',
    'nocomment',
    'omnicajs',
    'oneline',
    'pcss',
    'playform',
    'poppanator',
    'rehype',
    'renminbi',
    'shiki',
    'shikijs',
    'sonarjs',
    'specv',
    'firstsecond',
    'styl',
    'tinyexec',
    'tses',
    'uncategorized',
    'undici',
    'usefathom',
    'vimrc',
  ],
  ignorePaths: [
    '.github',
    'changelog.md',
    'license',
    'pnpm-lock.yaml',
    'release.md',
    'tsconfig.json',
    'vendor',
  ],
  dictionaries: ['css', 'html', 'node', 'npm', 'typescript'],
  useGitignore: true,
  language: 'en',
})
